use_frameworks!

platform :ios, '13.0'

target 'GGXCozeChat_Example' do
  pod 'GGXCozeChat', :path => '../'

#  pod 'GGXSwiftExtension' , :path => '~/Documents/GitHub/ggxswiftexten'  #工具扩展类
#  pod 'GXSwiftNetwork', :path => '~/Documents/GitHub/gxswiftnetwork' #网络请求类
  pod 'GGXRSA'
#  , :path => '~/Documents/GitHub/GGXRSA'
#  pod 'IKEventSource'
#  pod 'PTDebugView'
  target 'GGXCozeChat_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
