use_frameworks!

platform :ios, '13.0'

target 'GGXCozeChat_Example' do
  pod 'GGXCozeChat', :path => '../'

#  pod 'GXSwiftNetwork', :path => '~/Documents/GitHub/gxswiftnetwork' #网络请求类
  
#  pod 'IKEventSource'
  
  target 'GGXCozeChat_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
